info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-23T15:59:49.957Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-23T15:59:55.661Z"}
info: Connected to the database. {"timestamp":"2022-11-23T15:59:58.202Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-23T16:00:01.893Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-23T16:00:09.422Z"}
info: Connected to the database. {"timestamp":"2022-11-23T16:00:11.970Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-23T16:00:21.135Z"}
info: Connected to the database. {"timestamp":"2022-11-23T16:00:23.823Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-23T16:06:14.234Z"}
info: Connected to the database. {"timestamp":"2022-11-23T16:06:19.434Z"}
error: 
    status - 500 
    message - Error: Already Exist EmailId
    at _callee$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:7:11)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-23T16:09:33.281Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-23T16:41:46.316Z"}
info: Connected to the database. {"timestamp":"2022-11-23T16:41:49.259Z"}
error: 
    status - 500 
    message - TypeError: UserService.login is not a function
    at _callee2$ (D:\NodeJS\FundoNotes\src\controllers\/user.controller.js:32:36)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at login (D:\NodeJS\FundoNotes\src\controllers\/user.controller.js:30:20)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\NodeJS\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\NodeJS\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\NodeJS\FundoNotes\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\NodeJS\FundoNotes\node_modules\raw-body\index.js:231:16)
    at done (D:\NodeJS\FundoNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\NodeJS\FundoNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-23T16:44:57.878Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-23T16:45:44.118Z"}
info: Connected to the database. {"timestamp":"2022-11-23T16:45:47.035Z"}
error: 
    status - 500 
    message - Error: Enter Valid EmailId
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:25:11)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-23T16:46:04.295Z"}
error: 
    status - 500 
    message - Error: Enter Valid EmailId
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:25:11)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-23T16:46:48.710Z"}
error: 
    status - 500 
    message - Error: Enter valid Password
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:22:13)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-23T16:48:29.751Z"}
error: 
    status - 500 
    message - Error: Enter Valid EmailId
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:25:11)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-23T16:48:49.911Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-24T02:45:56.014Z"}
info: Connected to the database. {"timestamp":"2022-11-24T02:45:58.943Z"}
error: 
    status - 500 
    message - ValidationError: "password" length must be at least 8 characters long 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T02:46:35.860Z"}
error: 
    status - 500 
    message - ValidationError: "password" length must be less than or equal to 15 characters long 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T02:47:34.058Z"}
error: 
    status - 500 
    message - ValidationError: "firstname" is required 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T03:11:44.016Z"}
error: 
    status - 500 
    message - ValidationError: "email" is required 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T03:12:00.140Z"}
error: 
    status - 500 
    message - ValidationError: "lastname" is required 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T03:12:10.587Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T03:12:28.692Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-24T03:29:15.332Z"}
info: Connected to the database. {"timestamp":"2022-11-24T03:29:17.959Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-24T03:30:13.856Z"}
info: Connected to the database. {"timestamp":"2022-11-24T03:30:16.452Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-24T13:20:07.707Z"}
info: Connected to the database. {"timestamp":"2022-11-24T13:20:11.695Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-24T14:09:47.674Z"}
info: Connected to the database. {"timestamp":"2022-11-24T14:09:57.460Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:208:17)
    at D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:26:33)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T14:10:58.802Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-24T14:17:42.761Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-24T14:17:47.549Z"}
info: Connected to the database. {"timestamp":"2022-11-24T14:17:50.021Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-24T14:18:00.852Z"}
info: Connected to the database. {"timestamp":"2022-11-24T14:18:03.394Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:208:17)
    at D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:26:33)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T14:18:11.929Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-24T14:19:58.129Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-24T14:20:08.744Z"}
info: Connected to the database. {"timestamp":"2022-11-24T14:20:11.261Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:208:17)
    at D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:27:33)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T14:20:25.862Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-24T14:21:08.479Z"}
info: Connected to the database. {"timestamp":"2022-11-24T14:21:11.253Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-24T14:21:23.839Z"}
info: Connected to the database. {"timestamp":"2022-11-24T14:21:28.969Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:208:17)
    at D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:27:33)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T14:21:32.193Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-24T14:24:01.271Z"}
info: Connected to the database. {"timestamp":"2022-11-24T14:24:03.964Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:208:17)
    at D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:27:33)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T14:24:12.511Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-24T14:43:30.072Z"}
info: Connected to the database. {"timestamp":"2022-11-24T14:43:32.966Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-24T14:48:52.258Z"}
info: Connected to the database. {"timestamp":"2022-11-24T14:49:00.508Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-24T14:49:29.323Z"}
info: Connected to the database. {"timestamp":"2022-11-24T14:49:33.590Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-24T14:54:07.496Z"}
info: Connected to the database. {"timestamp":"2022-11-24T14:54:11.168Z"}
