error: 
    status - 500 
    message - Error: Already Exist EmailId
    at _callee$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:7:11)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-23T16:09:33.281Z"}
error: 
    status - 500 
    message - TypeError: UserService.login is not a function
    at _callee2$ (D:\NodeJS\FundoNotes\src\controllers\/user.controller.js:32:36)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at login (D:\NodeJS\FundoNotes\src\controllers\/user.controller.js:30:20)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\NodeJS\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\NodeJS\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\NodeJS\FundoNotes\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\NodeJS\FundoNotes\node_modules\raw-body\index.js:231:16)
    at done (D:\NodeJS\FundoNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\NodeJS\FundoNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-23T16:44:57.878Z"}
error: 
    status - 500 
    message - Error: Enter Valid EmailId
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:25:11)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-23T16:46:04.295Z"}
error: 
    status - 500 
    message - Error: Enter Valid EmailId
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:25:11)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-23T16:46:48.710Z"}
error: 
    status - 500 
    message - Error: Enter valid Password
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:22:13)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-23T16:48:29.751Z"}
error: 
    status - 500 
    message - Error: Enter Valid EmailId
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:25:11)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-23T16:48:49.911Z"}
error: 
    status - 500 
    message - ValidationError: "password" length must be at least 8 characters long 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T02:46:35.860Z"}
error: 
    status - 500 
    message - ValidationError: "password" length must be less than or equal to 15 characters long 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T02:47:34.058Z"}
error: 
    status - 500 
    message - ValidationError: "firstname" is required 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T03:11:44.016Z"}
error: 
    status - 500 
    message - ValidationError: "email" is required 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T03:12:00.140Z"}
error: 
    status - 500 
    message - ValidationError: "lastname" is required 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T03:12:10.587Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T03:12:28.692Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:208:17)
    at D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:26:33)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T14:10:58.802Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:208:17)
    at D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:26:33)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T14:18:11.929Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:208:17)
    at D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:27:33)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T14:20:25.862Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:208:17)
    at D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:27:33)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T14:21:32.193Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:208:17)
    at D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:27:33)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T14:24:12.511Z"}
error: 
    status - 500 
    message - Error: secretOrPrivateKey must have a value
    at Object.sign (D:\NodeJS\FundoNotes\node_modules\jsonwebtoken\sign.js:107:20)
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:29:23)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-25T07:10:34.038Z"}
error: 
    status - 500 
    message - Error: secretOrPrivateKey must have a value
    at Object.sign (D:\NodeJS\FundoNotes\node_modules\jsonwebtoken\sign.js:107:20)
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:29:23)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-25T07:11:10.836Z"}
error: 
    status - 500 
    message - ValidationError: "descrption" is required 
    url - /api/v1/note/create 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-25T08:07:53.977Z"}
error: 
    status - 500 
    message - ValidationError: "descrption" is required 
    url - /api/v1/note/create 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-25T08:12:03.920Z"}
error: 
    status - 500 
    message - ValidationError: "descrption" is required 
    url - /api/v1/note/create 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-25T08:12:27.096Z"}
error: 
    status - 500 
    message - ValidationError: "descrption" is required 
    url - /api/v1/note/create 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-25T08:13:00.749Z"}
error: 
    status - 500 
    message - ValidationError: "descrption" is required 
    url - /api/v1/note/create 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-25T08:13:36.725Z"}
error: 
    status - 500 
    message - TypeError: NoteService.updateNote is not a function
    at _callee4$ (D:\NodeJS\FundoNotes\src\controllers\/note.controller.js:70:38)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at updateNote (D:\NodeJS\FundoNotes\src\controllers\/note.controller.js:68:26)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\NodeJS\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at param (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:365:14)
    at param (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:421:3)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\NodeJS\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\NodeJS\FundoNotes\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\NodeJS\FundoNotes\node_modules\raw-body\index.js:231:16)
    at done (D:\NodeJS\FundoNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\NodeJS\FundoNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/note/6380b93291636b4c407bc2aa 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-11-25T13:07:19.792Z"}
error: 
    status - 500 
    message - ReferenceError: Notes is not defined
    at _callee6$ (D:\NodeJS\FundoNotes\src\services\/note.service.js:42:45)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.archiveNote (D:\NodeJS\FundoNotes\src\services\/note.service.js:42:25)
    at _callee6$ (D:\NodeJS\FundoNotes\src\controllers\/note.controller.js:108:36)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at archiveNote (D:\NodeJS\FundoNotes\src\controllers\/note.controller.js:106:26)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\NodeJS\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at param (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:365:14)
    at param (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:421:3)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\NodeJS\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at jsonParser (D:\NodeJS\FundoNotes\node_modules\body-parser\lib\types\json.js:119:7) 
    url - /api/v1/note/6380b89887c0f233ecdfa24e/archive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-11-28T08:15:38.091Z"}
error: 
    status - 500 
    message - ReferenceError: Notes is not defined
    at _callee6$ (D:\NodeJS\FundoNotes\src\services\/note.service.js:42:45)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.archiveNote (D:\NodeJS\FundoNotes\src\services\/note.service.js:42:25)
    at _callee6$ (D:\NodeJS\FundoNotes\src\controllers\/note.controller.js:108:36)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at archiveNote (D:\NodeJS\FundoNotes\src\controllers\/note.controller.js:106:26)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\NodeJS\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at param (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:365:14)
    at param (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:421:3)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\NodeJS\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\NodeJS\FundoNotes\node_modules\body-parser\lib\read.js:137:5 
    url - /api/v1/note/6380b89887c0f233ecdfa24e/archive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-11-28T08:17:36.091Z"}
error: 
    status - 500 
    message - ReferenceError: Notes is not defined
    at _callee6$ (D:\NodeJS\FundoNotes\src\services\/note.service.js:42:45)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.archiveNote (D:\NodeJS\FundoNotes\src\services\/note.service.js:42:25)
    at _callee6$ (D:\NodeJS\FundoNotes\src\controllers\/note.controller.js:108:36)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at archiveNote (D:\NodeJS\FundoNotes\src\controllers\/note.controller.js:106:26)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\NodeJS\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at param (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:365:14)
    at param (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:421:3)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\NodeJS\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\NodeJS\FundoNotes\node_modules\body-parser\lib\read.js:137:5 
    url - /api/v1/note/6380b89887c0f233ecdfa24e/archive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-11-28T11:32:35.955Z"}
error: 
    status - 500 
    message - ReferenceError: Notes is not defined
    at _callee6$ (D:\NodeJS\FundoNotes\src\services\/note.service.js:42:45)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.archiveNote (D:\NodeJS\FundoNotes\src\services\/note.service.js:42:25)
    at _callee6$ (D:\NodeJS\FundoNotes\src\controllers\/note.controller.js:108:36)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at archiveNote (D:\NodeJS\FundoNotes\src\controllers\/note.controller.js:106:26)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\NodeJS\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at param (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:365:14)
    at param (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:421:3)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\NodeJS\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\NodeJS\FundoNotes\node_modules\body-parser\lib\read.js:137:5 
    url - /api/v1/note/6380b89887c0f233ecdfa24e/archive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-11-28T11:34:55.802Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee6$ (D:\NodeJS\FundoNotes\src\services\/note.service.js:50:7)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/6380b89887c0f233ecdfa24e/archive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-11-28T11:46:18.397Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of null (reading 'length')
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:25:12)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-29T09:19:41.911Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/note/create 
      method - POST 
      IP - ::1
     {"timestamp":"2022-11-29T09:53:56.836Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'email')
    at _callee$ (D:\NodeJS\FundoNotes\src\middlewares\/auth.middleware.js:23:28)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/create 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-29T09:59:25.414Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'email')
    at _callee$ (D:\NodeJS\FundoNotes\src\middlewares\/auth.middleware.js:23:28)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/create 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-29T10:09:01.602Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'email')
    at _callee$ (D:\NodeJS\FundoNotes\src\middlewares\/auth.middleware.js:23:28)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/create 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-29T10:13:29.523Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/note/allNote 
      method - GET 
      IP - ::1
     {"timestamp":"2022-11-29T10:18:40.378Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'email')
    at _callee$ (D:\NodeJS\FundoNotes\src\middlewares\/auth.middleware.js:24:23)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/create 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-29T11:38:24.921Z"}
error: 
    status - 500 
    message - ObjectParameterError: Parameter "filter" to find() must be an object, got chetan456@gmail.com
    at model.Query.Query.find (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:2098:16)
    at Function.find (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\model.js:2157:13)
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/note.service.js:11:29)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.getAllNotes (D:\NodeJS\FundoNotes\src\services\/note.service.js:10:25)
    at _callee2$ (D:\NodeJS\FundoNotes\src\controllers\/note.controller.js:32:36)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at getAllNotes (D:\NodeJS\FundoNotes\src\controllers\/note.controller.js:30:26)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at _callee$ (D:\NodeJS\FundoNotes\src\middlewares\/auth.middleware.js:27:5)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/allNote 
    method - GET 
    IP - ::1
   {"timestamp":"2022-11-29T11:42:59.754Z"}
error: 
    status - 500 
    message - ObjectParameterError: Parameter "filter" to find() must be an object, got chetan456@gmail.com
    at model.Query.Query.find (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:2098:16)
    at Function.find (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\model.js:2157:13)
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/note.service.js:11:29)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.getAllNotes (D:\NodeJS\FundoNotes\src\services\/note.service.js:10:25)
    at _callee2$ (D:\NodeJS\FundoNotes\src\controllers\/note.controller.js:32:36)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at getAllNotes (D:\NodeJS\FundoNotes\src\controllers\/note.controller.js:30:26)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at _callee$ (D:\NodeJS\FundoNotes\src\middlewares\/auth.middleware.js:27:5)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/allNote 
    method - GET 
    IP - ::1
   {"timestamp":"2022-11-29T11:44:00.344Z"}
error: 
    status - 500 
    message - ReferenceError: UserID is not defined
    at _callee3$ (D:\NodeJS\FundoNotes\src\services\/note.service.js:17:52)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.getNote (D:\NodeJS\FundoNotes\src\services\/note.service.js:16:21)
    at _callee3$ (D:\NodeJS\FundoNotes\src\controllers\/note.controller.js:51:36)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at getNote (D:\NodeJS\FundoNotes\src\controllers\/note.controller.js:49:22)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at _callee$ (D:\NodeJS\FundoNotes\src\middlewares\/auth.middleware.js:27:5)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/6385f01c9c3f9d23f831302e 
    method - GET 
    IP - ::1
   {"timestamp":"2022-11-29T14:00:07.035Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ id: '6385f01c9c3f9d23f831302e', userID: undefined }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/6385f01c9c3f9d23f831302e 
    method - GET 
    IP - ::1
   {"timestamp":"2022-11-29T14:00:51.524Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ id: '6385f01c9c3f9d23f831302e', userID: 'chetan456@gmail.com' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/6385f01c9c3f9d23f831302e 
    method - GET 
    IP - ::1
   {"timestamp":"2022-11-29T14:02:31.033Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ id: '6385f01c9c3f9d23f831302e', userID: 'chetan456@gmail.com' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/6385f01c9c3f9d23f831302e 
    method - GET 
    IP - ::1
   {"timestamp":"2022-11-29T14:11:16.127Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ id: '6385f01c9c3f9d23f831302e', userID: 'chetan456@gmail.com' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/6385f01c9c3f9d23f831302e 
    method - GET 
    IP - ::1
   {"timestamp":"2022-11-29T14:13:14.525Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ id: '6385f01c9c3f9d23f831302e', userID: 'chetan456@gmail.com' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/6385f01c9c3f9d23f831302e 
    method - GET 
    IP - ::1
   {"timestamp":"2022-11-29T14:15:33.695Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ id: '6385f01c9c3f9d23f831302e', userID: 'chetan456@gmail.com' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/6385f01c9c3f9d23f831302e 
    method - GET 
    IP - ::1
   {"timestamp":"2022-11-29T14:16:48.637Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ id: '6385f01c9c3f9d23f831302e', userID: 'chetan456@gmail.com' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/6385f01c9c3f9d23f831302e 
    method - GET 
    IP - ::1
   {"timestamp":"2022-11-29T14:18:56.928Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ id: '6385f01c9c3f9d23f831302e', userID: 'chetan456@gmail.com' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/6385f01c9c3f9d23f831302e 
    method - GET 
    IP - ::1
   {"timestamp":"2022-11-29T14:21:42.593Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/note/63860d936f713d2b740c2052/trash 
      method - PUT 
      IP - ::1
     {"timestamp":"2022-11-29T15:08:38.881Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ id: '63860d936f713d2b740c2052', userID: 'chetan456@gmail.com' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/63860d936f713d2b740c2052 
    method - GET 
    IP - ::1
   {"timestamp":"2022-11-30T02:33:43.246Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/note/63860d936f713d2b740c2052/archive 
      method - PUT 
      IP - ::1
     {"timestamp":"2022-11-30T02:34:05.976Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ id: '63860d936f713d2b740c2052', userID: 'chetan456@gmail.com' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\NodeJS\FundoNotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/note/63860d936f713d2b740c2052 
    method - GET 
    IP - ::1
   {"timestamp":"2022-11-30T05:28:33.494Z"}
error: 
    status - 500 
    message - Error: Enter Password is invalid
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:32:13)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-30T11:21:14.080Z"}
error: 
    status - 500 
    message - Error: Enter Password is invalid
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:32:13)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-30T12:55:02.101Z"}
error: 
    status - 500 
    message - Error: Enter Password is invalid
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:32:13)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-30T12:55:09.742Z"}
error: 
    status - 500 
    message - Error: Enter Password is invalid
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:32:13)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-30T12:55:16.386Z"}
error: 
    status - 500 
    message - Error: Enter Password is invalid
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:32:13)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-30T12:55:45.078Z"}
error: 
    status - 500 
    message - Error: Enter Password is invalid
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:32:13)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-30T12:58:43.110Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token } in JSON at position 41
    at JSON.parse (<anonymous>)
    at parse (D:\NodeJS\FundoNotes\node_modules\body-parser\lib\types\json.js:89:19)
    at D:\NodeJS\FundoNotes\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\NodeJS\FundoNotes\node_modules\raw-body\index.js:231:16)
    at done (D:\NodeJS\FundoNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\NodeJS\FundoNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/forgotpassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-30T15:49:18.011Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token } in JSON at position 41
    at JSON.parse (<anonymous>)
    at parse (D:\NodeJS\FundoNotes\node_modules\body-parser\lib\types\json.js:89:19)
    at D:\NodeJS\FundoNotes\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\NodeJS\FundoNotes\node_modules\raw-body\index.js:231:16)
    at done (D:\NodeJS\FundoNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\NodeJS\FundoNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/forgotpassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-12-01T02:02:10.957Z"}
error: 
    status - 500 
    message - Error: Enter Password is invalid
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:33:13)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-12-01T07:46:39.981Z"}
error: 
    status - 500 
    message - Error: Enter Password is invalid
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:33:13)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-12-01T07:47:31.647Z"}
error: 
    status - 500 
    message - Error: Enter Password is invalid
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:33:13)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-12-01T07:49:48.750Z"}
error: 
    status - 500 
    message - ValidationError: "firstname" length must be at least 4 characters long 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-12-01T08:33:36.203Z"}
error: 
    status - 500 
    message - ValidationError: "lastname" length must be at least 4 characters long 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-12-01T08:33:36.219Z"}
error: 
    status - 500 
    message - ValidationError: "email" must be a valid email 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-12-01T08:33:36.233Z"}
error: 
    status - 500 
    message - ValidationError: "password" length must be at least 8 characters long 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-12-01T08:33:36.251Z"}
error: 
    status - 500 
    message - ValidationError: "password" is not allowed to be empty 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-12-01T08:33:36.271Z"}
error: 
    status - 500 
    message - ValidationError: "firstname" length must be at least 4 characters long 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-12-01T08:39:47.263Z"}
error: 
    status - 500 
    message - ValidationError: "lastname" length must be at least 4 characters long 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-12-01T08:39:47.276Z"}
error: 
    status - 500 
    message - ValidationError: "email" must be a valid email 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-12-01T08:39:47.291Z"}
error: 
    status - 500 
    message - ValidationError: "password" length must be at least 8 characters long 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-12-01T08:39:47.310Z"}
error: 
    status - 500 
    message - ValidationError: "password" length must be less than or equal to 15 characters long 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-12-01T08:39:47.326Z"}
error: 
    status - 500 
    message - ValidationError: "password" is not allowed to be empty 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-12-01T08:39:47.342Z"}
error: 
    status - 500 
    message - ValidationError: "firstname" is not allowed to be empty 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-12-01T08:39:47.357Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "shital2312345" fails to match the required pattern: /^(?=.*[a-z])(?=.*[A-Z])((?=.*[!@#&?/*~$^]{1})).{8,}$/ 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-12-01T12:20:11.689Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "sHital2312345" fails to match the required pattern: /^(?=.*[a-z])(?=.*[A-Z])((?=.*[!@#&?/*~$^]{1})).{8,}$/ 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-12-01T12:20:26.933Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "sHital@s" fails to match the required pattern: /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])((?=.*[!@#&?/*~$^]{1})).{8,}$/ 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-12-01T12:23:06.262Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "shital1@s" fails to match the required pattern: /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])((?=.*[!@#&?/*~$^]{1})).{8,}$/ 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-12-01T12:23:25.040Z"}
error: 
    status - 500 
    message - ValidationError: "password" length must be less than or equal to 15 characters long 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-12-01T12:25:23.361Z"}
error: 
    status - 500 
    message - ValidationError: "firstname" with value "valmik" fails to match the required pattern: /^[A-Z]{1}[a-z]/ 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-12-01T12:27:15.755Z"}
error: 
    status - 500 
    message - ValidationError: "firstname" length must be at least 4 characters long 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-12-01T12:27:26.432Z"}
